### ISSUE TITLE
ReadHydroStatic needs update for expanded input file

### ISSUE THREAD

**Issue by gbarter** [YingyiLiu/HAMS#12] opened 2021-05-21 10:39 UTC
Yingyi,

I think the reasons the tests are failing is that this read function:
https://github.com/YingyiLiu/HAMS/blob/master/SourceCode/HydroStatic.f90#L73

needs a new block for the quadratic damping that was recently added in the input files.  

I may not have all of my terms correct, but I can definitely see that the Wamit hst-file is wrong because it is getting written with the wrong data.

**Comment by YingyiLiu** [comment] 2021-05-21 11:14
Dear Garrett, Thanks for pointing that out. You are very much correct. It was due to I forgot to push the most recent commits to the repository. The problem is now fixed.

**Closed** 2021-05-22 12:51 UTC
